name: Build
on:
  push:
    branches:
      - main

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDD-HHmm'
      - name: Create empty release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.time.outputs.time }}
          body_path: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
    outputs:
      release_id: ${{ steps.release.outputs.id }}
  build:
    runs-on: ubuntu-latest
    needs: prepare_release
    steps:
      - name: Get more space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          swap-size-mb: 100
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Install deb deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: devscripts build-essential debhelper po4a gettext debootstrap libnss-mymachines live-boot-doc live-config-doc live-manual-html systemd-container qemu-user-static
          version: 1.0
      - name: Build live-build
        shell: bash
        run: |
          mkdir live-build && cd live-build
          git clone https://salsa.debian.org/amazingfate/live-build.git -b ubuntu-arm64 --depth=1
          cd live-build
          sudo apt -y install debhelper po4a gettext
          dpkg-buildpackage -us -uc
          sudo apt -y install ../live-build_*_all.deb
      - name: Build live iso
        shell: bash
        run: |
          mkdir iso-build && cd iso-build
          wget https://github.com/amazingfate/rk3588-live-iso/raw/main/lb-config.sh
          wget https://github.com/amazingfate/rk3588-live-iso/raw/main/additional-packages
          ./lb-config.sh
          sudo lb build
      - name: Rollback release
        if: failure() && needs.prepare_release.outputs.release_id != ''
        uses: author/action-rollback@stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.prepare_release.outputs.release_id }}
